# -*- coding: utf-8 -*-
"""ASR_metrics_dummyLibrespeech_Eng.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xVwowMn__-3IZO3PjkPVEdQ5sLv2nrcW

### ASR with clean small dataset:
- librispeech_asr_dummy provided on HuggingFace
### Metrics evaluated with dataset:
- WER
- RTF, Speedup

### Result:
Whisper model is benchmarked with LibriSpeech original dataset.

Current WER for dummy dataset is bit larger than the reported one for medium model.

| model/ metric   | original dataset | dummy dataset  |
|-----------------|------------------|----------------|
| tiny    WER     | 7 - 15 %         | 11.2 %         |
| medium  WER     | 2.9 - 6 %        | 6.6 %          |
|-----------------|------------------|----------------|
| tiny    speedUp |                  | 15.4x          |
| medium  speedUp |                  | 8.6x           |
"""

!pip uninstall -y torch torchaudio torchvision
!pip install -q torch torchaudio
!pip install -q faster-whisper datasets jiwer soundfile num2words

# confirm
import torch

print(torch.__version__)

x = torch.tensor([1,2,3])

print(x)

# import libs
import torch
import torchaudio
import time
from datasets import load_dataset
from faster_whisper import WhisperModel
import soundfile as sf
import re
from jiwer import (
    wer,
    Compose,
    ToLowerCase,
    RemovePunctuation,
    RemoveMultipleSpaces,
    Strip
)

# Load small librispeech_asr_dummy dataset

dataset = load_dataset(
    "hf-internal-testing/librispeech_asr_dummy",
    "clean",
    split="validation"
)

print(dataset)


# load WHISPER models: tiny & medium

model1 = WhisperModel(
    "tiny",
    device="cuda",
    compute_type="float16"
    #device="cpu",
    #compute_type="int8"
)

model2 = WhisperModel(
    "medium",
    device="cuda",
    compute_type="float16"
    #device="cpu",
    #compute_type="int8"
)

# Normalization 

basic_transform = Compose([
    ToLowerCase(),
    RemovePunctuation(),
    RemoveMultipleSpaces(),
    Strip()
])

number_map = {
    "20s": "twenties",
    "30s": "thirties",
    "40s": "forties",
    "50s": "fifties"
}

def normalize_numbers(text):

    for k, v in number_map.items():
        text = text.replace(k, v)
    return text

# ASR

references = []
predictions1 = []
predictions2 = []
total_processing_time1 = 0.0
total_processing_time2 = 0.0
total_audio_duration = 0.0

for sample in dataset:

    audio_array = sample["audio"]["array"]
    sample_rate = sample["audio"]["sampling_rate"]
    audio_duration = len(audio_array) / sample_rate
    total_audio_duration += audio_duration

    # save temporary wav
    sf.write(
        "temp.wav",
        audio_array,
        sample_rate,
        subtype="PCM_16"
    )
    
# ===========================================
 # with tiny model
    # note execution time:
    start = time.time()

    # transcribe
    segments1, info1 = model1.transcribe(
        "temp.wav",
        language="en"
    )
    segments1 = list(segments1)
    print(segments1)

    end = time.time()
    processing_time = end - start
    total_processing_time1 += processing_time

    predicted_text1 = " ".join(
        seg.text.strip()
        for seg in segments1
    )

    reference_text = sample["text"]

    predictions1.append(predicted_text1)
    references.append(reference_text)

# ===========================================
 # with medium model
    start2 = time.time()

    # transcribe
    segments2, info2 = model2.transcribe(
        "temp.wav",
        language="en"
    )
    segments2 = list(segments2)
    print(segments2)

    end2 = time.time()
    processing_time2 = end2 - start2
    total_processing_time2 += processing_time2

    predicted_text2 = " ".join(
        seg.text.strip()
        for seg in segments2
    )

    predictions2.append(predicted_text2)

print(len(references))
print(len(predictions1))
print(len(predictions2))

# apply normalizations

normalized_refs = []
normalized_preds1 = []
normalized_preds2 = []

for ref, pred1, pred2 in zip(
    references,
    predictions1,
    predictions2
):

    ref = basic_transform(ref)

    transformed_pred1 = basic_transform(pred1)
    transformed_pred2 = basic_transform(pred2)

    ref = normalize_numbers(ref)

    norm_pred1 = normalize_numbers(transformed_pred1)
    norm_pred2 = normalize_numbers(transformed_pred2)

    normalized_refs.append(ref)

    normalized_preds1.append(norm_pred1)
    normalized_preds2.append(norm_pred2)

print(len(normalized_preds1))
print(len(normalized_preds2))

# Compute Metrics: WER, Real-Time Factor (RTF), Sppedup

final_wer1 = wer(normalized_refs,normalized_preds1)
rtf1 = total_processing_time1/total_audio_duration
speedup1 = 1/rtf1

final_wer2 = wer(normalized_refs,normalized_preds2)
rtf2 = total_processing_time2/total_audio_duration
speedup2 = 1/rtf2  


print("\n========================")
print("with tiny model:")
print("FINAL WER:", final_wer1)
print("FINAL RTF:", rtf1)
print("FINAL SpeedUp:", speedup1 )
print("\n========================")
print("with Medium model:")
print("FINAL WER:", final_wer2)
print("FINAL RTF:", rtf2)
print("FINAL SpeedUp:", speedup2)


# let's see how normalization improved predictions

NUM_EXAMPLES = 3

for i in range(NUM_EXAMPLES):

    print("\n========================")
    print(f"Example {i+1}")
    print("========================")

    print("\nREFERENCE:")
    print(references[i])

    print("\nPREDICTION with tiny model:")
    print(predictions1[i])

    print("\nPREDICTION with medium model:")
    print(predictions2[i])

    print("\nNORMALIZED REFERENCE:")
    print(normalized_refs[i])

    print("\nNORMALIZED PREDICTION with tiny model:")
    print(normalized_preds1[i])

    print("\nNORMALIZED PREDICTION with medium model:")
    print(normalized_preds2[i])
